# config/services.yaml

parameters:
    uploads_directory: '%kernel.project_dir%/public/uploads/services'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $uploadsDirectory: '%uploads_directory%' # <-- injection du paramÃ¨tre

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
