# config/services.yaml

parameters:
    services_directory: '%kernel.project_dir%/public/uploads/services'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $servicesDirectory: '%services_directory%'

    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
